### ISSUE TITLE
Fix error when submitting new admin FastForward email

### ISSUE THREAD

**Issue by jlegrone** [Bernie-2016/ground-control#650] opened 2016-03-28 01:31 UTC
Getting error in MutationHandler `Cannot read property 'event_id' of undefined` when submitting new FastForward email, but logs show that emails are getting sent every time the submit button is clicked.

**Comment by bahoo** [comment] 2016-03-29 20:50
I still can't reproduce this, but should be fixed through #595 with disabling the button. Closing for now.

**Closed** 2016-03-29 20:50 UTC
Labels: priority-high, project-event-admin, project-fast-forward, type-bug
