### ISSUE TITLE
Implement a proper event creation form for administrative use

### ISSUE THREAD

**Issue by jlegrone** [Bernie-2016/ground-control#213] opened 2015-12-14 20:02 UTC
Right now we only need to support phonebank event types. We'll need to figure out which fields are required and provide default values for the rest.

**Comment by jlegrone** [comment] 2015-12-14 21:03
For now add new field to existing form.

**Comment by saikat** [comment] 2015-12-18 01:30
Closing this as a dupe of #204

**Closed by saikat** 2015-12-18 01:30 UTC
